# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14216093a9494ec7175763c0f6cb9dedc51e222bfd6e0479e76a376bd72da520f20b010551d4bc2915d21bc1399c4ac30f85e6ce87b19c5ad6602a3f3745b799

test:
  secret_key_base: 9e42bb3620dab7b5e7e574d8f4713841b16a5895e362021616d9602814321762c9656761a3498a2b9192e06e6d8e97563ce0142b1fd5a4c7874cc13efc4b6517

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
